# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

# Mod Properties
version=1.1.1+mc26
group=com.mrerenk
archives_base_name=mapdistancefix
java_version=25
mod_name=MapDistanceFix
mod_author=mrerenk
mod_id=mapdistancefix
license=MIT
credits=MrErenK
description=A very simple Minecraft Fabric mod that fixes map player indicators to always show the player's position and direction, even when outside map boundaries, making it much easier to navigate treasure maps and other map items
minecraft_version_range=>=26.1
minecraft_version=26.2

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
fabric_version=0.152.2+26.2
min_fabric_version=0.144.3+26.1
fabric_loader_version=0.18.6
loom_version=1.17-SNAPSHOT

# Extra Dependencies
# check these on https://linkie.shedaniel.dev/dependencies?loader=fabric&version=26.2
cloth_config_version=26.2.155
modmenu_version=20.0.0-beta.3

# NeoForge Properties
# check these on https://projects.neoforged.net/
neoforge_version=26.2.0.6-beta
moddev_version=2.0.141
neoforge_loader_version_range=[4,)
neo_form_version=26.2-1
