# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mod Properties
old_mod_version=1.0.8+mc1.17-1.19.1
new_mod_version=1.0.8+mc1.19.2-1.20.1
maven_group=com.mrerenk
archives_base_name=MapDistanceFix
old_minecraft_version_range=>=1.17 <=1.19.1
new_minecraft_version_range=>=1.19.2 <=1.20.1

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.92.6+1.20.1
new_min_fabric_version=0.77.0+1.19.2
old_min_fabric_version=0.36.0+1.17
